### ISSUE TITLE
MSYS2 build script

### ISSUE THREAD

**Issue by mh466lfa** [RolandHughes/ls-cs#10]
MSYS2 uses Arch Linux's build and packaging system. So the PKGBUILD for Manjaro/Arch Linux could be adapted for MSYS2.

**Comment by RolandHughes** [comment]
Honestly, MSYS2 is a non-starter. We will build native on Windows or not at all.

**Comment by mh466lfa** [comment]
CopperSpice has always supported the free and open source MinGW-w64 compiler. They even have their own MinGW-w64 distro called cs_mingw_w64. Based on your comments on the CMake build scripts, it seems you ripped the support for MinGW-w64 and dictated MSVC as the only supported compiler on Windows. I used to think your answer above is because of your misunderstandings about MSYS2. It turned out to be wrong.

**Comment by mh466lfa** [comment]
Btw, if you really misunderstood about MSYS2, then MSYS2 is a build environment. Please have a look at this:

https://www.msys2.org/docs/environments/

The package mingw-w64-lscs will target the MinGW-w64 environments only and since it is built using the MinGW-w64 compiler, it will target native Win32. Nothing non-native here. It will not link the POSIX compatibility layer, msys-2.0.dll.

Don't confuse MinGW with Cygwin!

**Comment by RolandHughes** [comment]
If it is used on Windows it will be a native build or they will run the Linux version under WSL or inside a VM. I'm not interested in this "being CopperSpice." They failed. This project is targeted at Embedded Systems/Medical Devices and the desktops used to create said devices. MinGW doesn't exist in the embedded systems world and I have no interest what-so-ever in creating a package for it.

Even if you managed to create a package for it today, it would be impossible to support in the coming months. Webkit will be purged and replaced by [Servo](https://servo.org/). Good luck trying to wedge Rust, WebGL, and WebGPU into MinGW.

MSYS2 is a dying market. WSL replaced any need for it on Windows 10, one can still find Oracle VirtualBox versions for Windows 7 to run Linux VM, and let us not forget [Docker](https://stefanscherer.github.io/yes-you-can-docker-on-windows-7/).
