### ISSUE TITLE
Will support for FreeBSD be removed?

### ISSUE THREAD

**Issue by chadchoi** [RolandHughes/ls-cs#21]
FreeBSD has Wayland and the original CopperSpice supports FreeBSD (X11, of course, because it doesn't support Wayland).

**Comment by RolandHughes** [comment]
I plan to run on FreeBSD, but that is a few miles down the road.

Look at the roadmap.

**AFTER** the move to Servo is when I will start testing/developing on other platforms.

Trying to make big changes to a code base while others are trying to add 50+ platforms is a recipe for a train wreck.
